// User Roles
const USER_ROLES = {
  USER: 'USER',
  DRIVER: 'DRIVER',
  ADMIN: 'ADMIN'
};

// Order Status
const ORDER_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DRIVER_EN_ROUTE: 'DRIVER_EN_ROUTE',
  ARRIVED_AT_PICKUP: 'ARRIVED_AT_PICKUP',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED_AT_DROPOFF: 'ARRIVED_AT_DROPOFF',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED'
};

// Payment Status
const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  NOT_PAID: 'NOT_PAID',
  REFUNDED: 'REFUNDED'
};

// KYC Status
const KYC_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED'
};

// Driver Status
const DRIVER_STATUS = {
  OFFLINE: 'OFFLINE',
  LOGGED_IN: 'LOGGED_IN',
  ONLINE: 'ONLINE',
  BUSY: 'BUSY'
};

// Dispute Status
const DISPUTE_STATUS = {
  OPEN: 'OPEN',
  PENDING: 'PENDING',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

// Notification Types
const NOTIFICATION_TYPES = {
  ORDER_STATUS_UPDATE: 'ORDER_STATUS_UPDATE',
  NEW_ORDER: 'NEW_ORDER',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',
  DISPUTE_UPDATE: 'DISPUTE_UPDATE',
  DRIVER_LOCATION_UPDATE: 'DRIVER_LOCATION_UPDATE'
};

// Vehicle Types
const VEHICLE_TYPES = {
  BIKE: 'BIKE',
  CAR: 'CAR',
  VAN: 'VAN',
  TRUCK: 'TRUCK'
};

// Payment Methods
const PAYMENT_METHODS = {
  CASH: 'CASH',
  CARD: 'CARD',
  TRANSFER: 'TRANSFER'
};

// Time Constants (in milliseconds)
const TIME_CONSTANTS = {
  LOCATION_UPDATE_INTERVAL: 10000, // 10 seconds
  LOCATION_TTL: 300000, // 5 minutes
  ORDER_PENDING_TIMEOUT: 86400000, // 24 hours
  ORDER_ACCEPT_TIMEOUT: 900000, // 15 minutes
  OTP_EXPIRY: 60000, // 60 seconds
  NOTIFICATION_RETRY_DELAY: 5000 // 5 seconds
};

// Redis Keys
const REDIS_KEYS = {
  DRIVER_LOCATION: (driverId) => `driver:location:${driverId}`,
  USER_SOCKET: (userId) => `user:socket:${userId}`,
  DELIVERY_TRACKING: (deliveryId) => `delivery:tracking:${deliveryId}`,
  OTP: (email) => `otp:${email}`,
  RATE_LIMIT: (ip) => `rate_limit:${ip}`,
  CACHE: (key) => `cache:${key}`
};

// Error Codes
const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  KYC_PENDING: 'KYC_PENDING',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  DRIVER_NOT_AVAILABLE: 'DRIVER_NOT_AVAILABLE'
};

module.exports = {
  USER_ROLES,
  ORDER_STATUS,
  PAYMENT_STATUS,
  KYC_STATUS,
  DRIVER_STATUS,
  DISPUTE_STATUS,
  NOTIFICATION_TYPES,
  VEHICLE_TYPES,
  PAYMENT_METHODS,
  TIME_CONSTANTS,
  REDIS_KEYS,
  ERROR_CODES
};